# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 04:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('participant_id', models.IntegerField()),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
