# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_honors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='participant_id',
            field=models.CharField(max_length=255),
        ),
    ]
