# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-25 04:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_attendance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='attendance',
        ),
    ]
